#services:
#    oc_platform.example:
#        class: OC\PlatformBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
# src/OC/PlatformBundle/Resources/config/services.yml

services:
    oc_platform.doctrine.notification:
        class: OC\PlatformBundle\DoctrineListener\ApplicationNotification
        arguments: [@mailer]
        tags:
            - { name: doctrine.event_listener, event: postPersist }
     
    oc_platform.antispam:
        class:     OC\PlatformBundle\Antispam\OCAntispam
        arguments: [@mailer, %locale%, 50]
        tags:
            -  { name: twig.extension }
        
    oc_platform.ckeditor:            
        class: OC\PlatformBundle\Form\Type\CkeditorType
        tags:
            - { name: form.type, alias: ckeditor }
            
    oc_platform.beta.html:
        class: OC\PlatformBundle\Beta\BetaHTML
        
    oc_platform.beta.listener:
        class: OC\PlatformBundle\Beta\BetaListener
        arguments: [@oc_platform.beta.html, "2015-12-20"]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: processBeta }

    oc_platform.json_paramconverter:
        class: OC\PlatformBundle\ParamConverter\JsonParamConverter
        tags:
            - { name: request.param_converter }